//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentHistory
    {
        public int AssignmentHistoryId { get; set; }
        public int AssignmentId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public int ScoreEarned { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Student Student { get; set; }
    }
}
