//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentViewDBEntities : DbContext
    {
        public StudentViewDBEntities()
            : base("name=StudentViewDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssignmentHistory> AssignmentHistories { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<EnrollmentHistory> EnrollmentHistories { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
